### ISSUE TITLE
More details wrt the training?

### ISSUE THREAD

**Issue by SiyuanHuang95** [daswer123/Voyager_chekpoit#1]
Hi thanks for your sharing!

Could you provide more practical details wrt the env setting and training?

Like hardware usage, training time, etc.

Also, during training, do we need to keep the Minecraft GUI alive or in the front?

Bests

**Comment by daswer123** [comment]
Of course, the setup was exactly according to the guide from the original repo.The only thing I used was venv for python libraries. 
Used azure_login.

As I understand it all goes through openAI and computer power is almost not involved in learning. It took about 6 hours to learn.
Hardware: Win10, i9-9900k and RTX 3090.

I used F3+P to keep minecraft from pausing. You can minimize the window and do your business, the main thing is that the game is not paused.

I took a little look at voyager.py and there is a function `inference`, through it you can set your tasks.
Here is my `start.py` in main folder
```
from voyager import Voyager

# you can also use mc_port instead of azure_login, but azure_login is highly recommended
azure_login = {
    "client_id": "HIDDEN",
    "redirect_url": "https://127.0.0.1/auth-response",
    "secret_value": "",
    "version": "fabric-loader-0.14.18-1.19", # the version Voyager is tested on,
}

openai_api_key = "HIDDEN"
mc_port = 14266


voyager = Voyager(
    azure_login=azure_login,
    # mc_port=mc_port,
    resume=True, # If you stop train you need this property to resume
    openai_api_key=openai_api_key,
)

# start lifelong learning, already done
# voyager.learn()

# After a training, you can set your own goal. 
voyager.inference("Chop wood by hand, craft a workbench and create a wooden axe")
```

**Comment by SiyuanHuang95** [comment]
Thanks for your quick reply.

"""
I used F3+P to keep minecraft from pausing. You can minimize the window and do your business, the main thing is that the game is not paused.
"""

I am using Ubuntu, every time I would like to do something else, Minecraft is paused somehow, I am quite confused about that. Would you have some suggestion for this.

Since the most port is done with OpenAI API, I guess the computer hardware is not required at all. And the skills could be taken as the summarization of agent's experiences with OpenAI?

**Comment by SiyuanHuang95** [comment]
BTW, I am wondering how you save those logs shown in your logs folder, were they enabled by Voyager?

These logs do help me understand the whole pipeline since I currently do not have access to the ChatGPT-4.

However, one minor fault would be there are many unrecognized characteristics like: (:-0)

```
[07:12:29] [Server thread/INFO]: [bot: Óñòàíîâëåíî çíà÷åíèå èãðîâîãî ïðàâèëà doTileDrops: false]
```

Also, that would be better if you could clean up the logs for those unnecessary.


Anyway,

Thanks for your sharing!

**Comment by daswer123** [comment]
I looked at me these logs are displayed correctly, but in my language (Russian), when learning forgot to change the language in minecraft :)

`Since the most port is done with OpenAI API, I guess the computer hardware is not required at all. And the skills could be taken as the summarization of agent's experiences with OpenAI?`

It turns out so, and because of this task takes a lot of time and requires access to GPT-4. In general now it is very expensive, the technology is interesting, but slow and expensive.

**Comment by SiyuanHuang95** [comment]
Thanks for your update!

**Comment by SiyuanHuang95** [comment]
Also, I have a follow-up question:

When the learning is on-going, would the agent in Minecraft also moves and takes actions as done in the codes per LAN? Or the exploration is just done in the backend?

**Comment by daswer123** [comment]
As I understand it, it works like this:
First, the agent goes to the LAN server and initializes itself, its inventory and where it is located. Then he starts initializing the task on the backend, splits the task into subtasks, analyzes the inventory and where it is, loads the appropriate skills. Then the code for the task is generated through a set of agents. After that the bot on LAN server tries to execute the code and get the result. If the desired item is obtained, described in the task, the code is written to the skill on the backend and can be used later for another task.

**Comment by SiyuanHuang95** [comment]
Thanks for your reply.

I can understand the pipeline of Voyager, but I am curious to find that the agent inside the simulator did not move actually, but the Voyager could continuously learn something. In. In other words, the simulator's frontend and backend are separated in some way. Was that also the case you met, or was something wrong in my setting?

Bests
