### ISSUE TITLE
Corresponding word sharing

### ISSUE THREAD

**Issue by SiyuanHuang95** [daswer123/Voyager_chekpoit#2]
Hi, thanks for your sharing again!

From the Voyager framework, it seems that the learned skills are sometimes depending on the items obtained in Minecraft, e.g. inventory or chest. So I am wondering, whether your Minecraft world could also be shared correspondingly?

Bests

**Comment by daswer123** [comment]
As I understand it, in the process of observing learning. the learn function contains a learning program already set, so there is a limit of 160 iterations, I have tried to continue learning, but it improves the existing functions and repeats the learning program.
Inference allows you to set the task yourself and as I understand it can learn new skills and use them later.

**Comment by SiyuanHuang95** [comment]
Clear, thanks a lot!
