### ISSUE TITLE
Iteration limit reached

### ISSUE THREAD

**Issue by changliucoding** [daswer123/Voyager_chekpoit#3]
Hi! thanks for sharing your ckpt.

When I am using your file, I encountered a problem. like this 

Loading Action Agent from my_dir/action
Loading Curriculum Agent from my_dir/curriculum
Loading Skill Manager from my_dir/skill
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 8232.
Server started on port 3000

Iteration limit reached

Then it stuck there. I use mc_port instead of azure, and I use voyager.learn() try to run, could these two be the issue? I look forward to hearing from you, many thanks!

**Comment by daswer123** [comment]
No, you need to go into vojager.py and find the variable max_iteration and increase it by as much as you need.

To start your task, follow the instructions, taken from the original repo
```
Run task decomposition
task = "YOUR TASK" # e.g. "Craft a diamond pickaxe"
sub_goals = voyager.decompose_task(task=task)
voyager.inference(sub_goals=sub_goals)

```

**Comment by changliucoding** [comment]
> No, you need to go into vojager.py and find the variable max_iteration and increase it by as much as you need.
> 
> To start your task, follow the instructions, taken from the original repo
> 
> ```
> Run task decomposition
> task = "YOUR TASK" # e.g. "Craft a diamond pickaxe"
> sub_goals = voyager.decompose_task(task=task)
> voyager.inference(sub_goals=sub_goals)
> ```

thanks! that works! 👍
